[project]
name = "event-insights"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn",
  "pydantic>=2",
  "scikit-learn",
  "azure-functions",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
